### ISSUE TITLE
Refactor: user-routes errorHandler 적용

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_BE#43]
## ☕ 기능
- user-routes errorHandler 적용 및 성공 코드 수정
- post pagination 적용

## 🪴 TODO

- [x] Refactor: errorHandler 적용
- [x] Refactor: status code 수정
- [x] Feat: getUserPosts Pagination 적용
