### ISSUE TITLE
Refactor: Coffee Auth middleware, getCoffeeInfo 수정

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker_BE#58]
## ☕ 기능
- Coffee Auth middleware 추가
- getCoffeeInfo 수정

## 🪴 TODO

- [x] Refactor: coffee Auth middleware
- [x] Refactor: getCoffeeInfo query 수정
- [x] Refactor: getCoffeeInfo res 수정
